### PR TITLE
Fix lazy context menu injection

### PR DESCRIPTION
**Pull request by colin273**
Fixes injection into the lazy-loaded context menu (using a quick-and-dirty patch I copied from SammCheese).

### CODE REVIEW

**Comment by lorencerri** [comment]
Thank you for the submission!

**Review by lorencerri — COMMENTED** [review]
Seems to be working as intended. The lazy-loading does make it so you need to click the image twice before it initializes, although that isn't much of an issue.

**Comment by colin273** [comment]
Hmm, it initializes right away for me without any further interaction. The first time I right click on an image, it takes a fraction of a second for the context menu item to appear on its own, and then after that it's just part of the context menu as you'd expect.

**Comment by lorencerri** [comment]
That's interesting, I wonder why it's doing that for me; Either way, it doesn't seem to be that big of an issue since lazy-loading is a large improvement

**Pull request merged**
